# Generated by Django 5.1.3 on 2024-12-05 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('tone', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
